# Generated by Django 5.1.4 on 2026-03-02 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_profile_profile_image"),
        ("products", "0016_remove_productimage_image_productimage_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="razorpay_payment_signature",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="color_variant",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="size_variant",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="color_variant",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="size_variant",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="shipping_address",
        ),
        migrations.CreateModel(
            name="UserCourse",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_delivered",
                    models.BooleanField(
                        default=False, verbose_name="是否已发送网盘链接"
                    ),
                ),
                (
                    "netdisk_link",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="发给用户的百度网盘链接",
                    ),
                ),
                (
                    "netdisk_password",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="提取码"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发货时间"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_owners",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchased_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户课程",
                "verbose_name_plural": "用户课程",
                "unique_together": {("user", "product")},
            },
        ),
    ]
