# Generated by Django 5.1.4 on 2026-03-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_remove_cart_razorpay_order_id_and_more"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
    ]
