# Generated by Django 5.1.4 on 2026-03-02 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_remove_cart_razorpay_order_id_and_more"),
        ("products", "0016_remove_productimage_image_productimage_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color_variant",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_variant",
        ),
        migrations.RemoveField(
            model_name="product",
            name="parent",
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "product")},
        ),
        migrations.AddField(
            model_name="product",
            name="full_content_link",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="完整资源链接（仅管理员填写）",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_free",
            field=models.BooleanField(default=False, verbose_name="是否免费"),
        ),
        migrations.AddField(
            model_name="product",
            name="netdisk_password",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="网盘提取码"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="preview_content",
            field=models.TextField(
                blank=True, null=True, verbose_name="预览内容（付费课程可看一部分）"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="preview_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="预览资源链接"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="ColorVariant",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="size_variant",
        ),
        migrations.DeleteModel(
            name="SizeVariant",
        ),
    ]
