# Generated by Django 5.1.4 on 2026-03-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_remove_product_color_variant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
    ]
