# Generated by Django 5.1.4 on 2026-03-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_remove_productimage_image_url_productimage_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="newest_product",
        ),
    ]
