# Generated by Django 5.1.4 on 2026-03-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_remove_product_newest_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
